### ISSUE TITLE
Examine Lag

### ISSUE THREAD

**Issue by RemieRichards** [sawu-tg/dragonroll#24]
Examining an NPC (in this case, Deepak the hologram weirdo) causes a lag spike, however debug does not report an increase in CPU.

**Comment by DaedalusGame** [comment]
Examining an NPC triggers a bunch of icon procs and sends the rsc to the person examining. Related?

**Comment by sawu-tg** [comment]
@DaedalusGame  possibly.

**Comment by RemieRichards** [comment]
Rsc fuckery is the worst.

**Comment by sawu-tg** [comment]
I removed most of the spammy icon procs, I guess I forgot a few.

**Comment by RemieRichards** [comment]
remove them all and cache them in a list not the bloody Rsc lol.

**Comment by sawu-tg** [comment]
@RemieRichards  Oh right :P

**Comment by sawu-tg** [comment]
https://github.com/sawu-tg/dragonroll/commit/e9f4dfb8abf62f46ae8edc73db4c1b11cb473230 partially fixes this. I'm closing this, but the icon displaying code needs an entire rewrite.
