### ISSUE TITLE
You can kick objects into Walls/Dense objects

### ISSUE THREAD

**Issue by RemieRichards** [sawu-tg/dragonroll#27]
Tested with the starting treasure chest, kicked it right into the wall.

**Comment by sawu-tg** [comment]
@RemieRichards  Obv your strength is too high and you kicked it right through the wall!

**Comment by RemieRichards** [comment]
@sawu-tg don't worry, I've got a fix batch coming that fixes most of the issues I've reported today.

**Comment by sawu-tg** [comment]
@RemieRichards oh, I was just about to fix them. Have you fixed the portal in water bug?

**Comment by RemieRichards** [comment]
@sawu-tg that one is free to fix, I didn't do that one.

**Comment by sawu-tg** [comment]
I'll get right on it then.
