### ISSUE TITLE
Character automatically moves southwest after leaping anywhere

### ISSUE THREAD

**Issue by DaedalusGame** [sawu-tg/dragonroll#38]

**Comment by sawu-tg** [comment]
@DaedalusGame Not sure if i'm going to call this a bug or not, I noticed this behaviour before, but I just went "yep thats a feature, he's totally climbing off things".

If you leap at something that is dense, or the character is unable to reach, it will move the character to the side.

**Comment by RemieRichards** [comment]
Nah this is definitely a bug.
