### ISSUE TITLE
Some flags don't work (or they all don't work)

### ISSUE THREAD

**Issue by sawu-tg** [sawu-tg/dragonroll#42]
I've no fucking clue (needs citation)

**Comment by DaedalusGame** [comment]
wat flags

**Comment by sawu-tg** [comment]
most flags added using mobAddFlags and mobRemFlags (and setFlag because it is called from mobAddFlags). Through debugging, adding something like ACTIVE_FLAG_STUNNED is instantly removed, regardless of the length you add to it.

**Comment by DaedalusGame** [comment]
setFlag(who.active_states, flag) doesn't really do anything when who.active_states is a number :V

**Comment by RemieRichards** [comment]
@DaedalusGame bitflags and bitfields are always numbers.

**Comment by DaedalusGame** [comment]
He's passing the bitfield into setFlag but byond doesn't support weak references.

**Comment by RemieRichards** [comment]
While that's true, that's still not what you said originally.

**Comment by DaedalusGame** [comment]
It's still accurate, as it would indeed work if who.active_states was a list.

**Comment by DaedalusGame** [comment]
processFlags is never called!?
