### ISSUE TITLE
portals are still broken

### ISSUE THREAD

**Issue by DaedalusGame** [sawu-tg/dragonroll#45]
entering any portal but Lobby A will throw a runtime

runtime error: Cannot modify null.loc.
proc name: triggerAction (/obj/trigger/portal/triggerAction)
  source file: trigger.dm,170
  usr: LordBistian (/mob/player)
  src: Zer\'fren the lava-land (/obj/trigger/portal)
  call stack:
Zer\'fren the lava-land (/obj/trigger/portal): triggerAction()
Zer\'fren the lava-land (/obj/trigger/portal): doTrigger()
Zer\'fren the lava-land (/obj/trigger/portal): Cross(LordBistian (/mob/player))

**Comment by DaedalusGame** [comment]
triggering var seemingly resets itself
wtf

**Comment by RemieRichards** [comment]
>LordBistian

**Comment by sawu-tg** [comment]
I'll look into this.

**Comment by sawu-tg** [comment]
Potentially fixed with bbb7053cd9b0e063f795874659f92b31c680d26a

Someone else needs to check and confirm

**Comment by DaedalusGame** [comment]
I swear to christ I was 13 when I registered get out

**Comment by sawu-tg** [comment]
I do not get this runtime, please retry with a fresh copy from the main repo @DaedalusGame.

**Comment by DaedalusGame** [comment]
It stopped when I fixed portals to not create extenders everytime you go through them

**Comment by sawu-tg** [comment]
@DaedalusGame Oh okay, good. Remember to tag this issue when you PR so it gets autoclosed
