### ISSUE TITLE
CPU Usage is 4x what it used to be

### ISSUE THREAD

**Issue by RemieRichards** [sawu-tg/dragonroll#64]
CPU: 208 | FPS: 15 | Total Atoms: 189018

**Comment by RemieRichards** [comment]
>processLiquids has 110 Realtime at 5 calls

**Comment by RemieRichards** [comment]
>all the other processXs are at 30~ Realtime

WHO TOUCHED AND BROKE THE EVERYTHING

**Comment by DaedalusGame** [comment]
who did this

**Comment by DaedalusGame** [comment]
processLiquids has normal realtime at normal calls

until the list finishes, then it flies up to 1200 realtime for 68 calls

**Comment by DaedalusGame** [comment]
:v::frowning::gun:

**Comment by sawu-tg** [comment]
Partially fixed in 2fc382eb79a2d1b0736d1407767299ceadc99220

If other similar issues occur (such as CPU rising abot 150) more issues should be made, otherwise an ongoing attempt at optimizations are still being done.

**Comment by RemieRichards** [comment]
@sawu-tg I fixed it properly.
CPU runs in around the 30s (20-40, so around 30) and the occasional spike that remains only takes things up to 50.

It was your INCREDIBLY bad processX() loops, fixing processObjects() alone alleviated 60% of the lag

**Comment by sawu-tg** [comment]
@RemieRichards  Thanks :+1:
