### ISSUE TITLE
Some Popups (Bord's) don't disappear 

### ISSUE THREAD

**Issue by RemieRichards** [sawu-tg/dragonroll#67]
![popuperror](https://cloud.githubusercontent.com/assets/4043781/8185825/738ca8be-143e-11e5-9cd2-3d35d0bf62c6.PNG)

Seemed to happen everytime, not sure though, I only tested 4 times.

**Comment by sawu-tg** [comment]
@RemieRichards Is it completely persistent, IE if you walk away and come back, is it still there?

**Comment by RemieRichards** [comment]
Didn't feel I needed to state that when I said "don't disappear"

**Comment by DaedalusGame** [comment]
this is a new one. GC probably broke it. STOP sdel()ing IMAGES YOU TAYOO

**Comment by sawu-tg** [comment]
Fixed in an unknown revision
