### ISSUE TITLE
Types failing to GC

### ISSUE THREAD

**Issue by RemieRichards** [sawu-tg/dragonroll#68]
<B>/datum/light_source</B>

<B>/obj/projectile</B>
*    /obj/projectile/spear 
*   /obj/projectile/manablast
*   /obj/projectile/toxinthrow

<B>/obj/effect</B>
* /obj/effect/pow
* /obj/effect/overlay/beam
*     /obj/effect/aoe_tile/bolster
*    /obj/effect/sparks
*   /obj/effect/fishingbouy

<B>/image</B>
<B>/datum/race/Jelly</B>

**Comment by sawu-tg** [comment]
I'm not sure about the /image and the jelly race, but several of those things have a spawned off/delayed deletion, that should be looked into.

**Comment by RemieRichards** [comment]
@sawu-tg while yes, it could be the timing of them (GC only waits 30 seconds) we shouldn't have to extend the patience time, those objects should simply be made to GC in a reasonable time.

to me it seems more like leftover references here, than bad timings.

**Comment by DaedalusGame** [comment]
getting real tired of a billion images being sdel'd and not resolving

solution: stop sdel'ing images

why are you doing that anyway

**Comment by RemieRichards** [comment]
@DaedalusGame ```/image``` are actually datums, they CAN GC properly.

**Comment by DaedalusGame** [comment]
they can, but they can can't remove their own references

**Comment by RemieRichards** [comment]
Yes they can, they can have procs defined on them, just like the rest.

**Comment by DaedalusGame** [comment]
images can what

**Comment by RemieRichards** [comment]
they are normal /datums. they can have a garbageCleanup() defined on them to clean any external references.

**Comment by sawu-tg** [comment]
Fixed (mostly) or entirely with d16df249d279ae6b645ddf73ffd64246ca972615 , and a patch to follow which improves the performance.
